# Generated by Django 6.0.1 on 2026-02-19 20:51

import apps.leads.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='URL amigable')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('cover_image', models.ImageField(help_text='Imagen principal del grid. Máx 5MB. JPG, PNG, WEBP.', upload_to='projects/%Y/%m/', validators=[apps.leads.validators.validate_image_file], verbose_name='Imagen de portada')),
                ('area', models.CharField(blank=True, help_text='Ej: 2.500 m²', max_length=100, verbose_name='Superficie')),
                ('duration', models.CharField(blank=True, help_text='Ej: 6 meses', max_length=100, verbose_name='Duración')),
                ('year', models.PositiveIntegerField(help_text='Año de realización del proyecto', verbose_name='Año')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar en la galería pública', verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, help_text='Aparece primero en la galería', verbose_name='Destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-is_featured', 'order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Máx 5MB. JPG, PNG, WEBP.', upload_to='projects/%Y/%m/', validators=[apps.leads.validators.validate_image_file], verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen del proyecto',
                'verbose_name_plural': 'Imágenes del proyecto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
