# Generated by Django 6.0.1 on 2026-03-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, help_text='Nombre del cliente o empresa. Dejar vacio si es confidencial.', max_length=200, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Detalla el trabajo realizado: funciones, tareas, materiales, soluciones tecnicas. Se muestra al abrir el proyecto en la web.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Nombre del proyecto. Breve y descriptivo (ej: "Aerotermia en chalet adosado").', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Describe la imagen brevemente (ej: "Vista del salon con suelo radiante"). Mejora accesibilidad y SEO.', max_length=200, verbose_name='Texto alternativo'),
        ),
    ]
