# Generated by Django 6.0.1 on 2026-03-09 14:01

import apps.leads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_slug_max_length_and_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(help_text='Imagen principal del grid. Min 800x400px. Máx 5MB. JPG, PNG, WEBP.', upload_to='projects/%Y/%m/', validators=[apps.leads.validators.validate_image_file], verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Min 600x400px. Máx 5MB. JPG, PNG, WEBP.', upload_to='projects/%Y/%m/', validators=[apps.leads.validators.validate_image_file], verbose_name='Imagen'),
        ),
    ]
