# Generated by Django 6.0 on 2026-01-14 16:52

import apps.leads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Máximo 5MB. Formatos: JPG, PNG, WEBP', null=True, upload_to='services/', validators=[apps.leads.validators.validate_image_file], verbose_name='Imagen representativa'),
        ),
    ]
