# Generated by Django 6.0 on 2026-01-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('slug', models.SlugField(unique=True, verbose_name='URL amigable')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, help_text='Para listados y SEO', max_length=200, verbose_name='Descripción corta')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono (opcional)', max_length=50, verbose_name='Icono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen representativa')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar en la web', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el sitio', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'name'],
            },
        ),
    ]
