# Generated by Django 6.0 on 2026-01-14 00:21

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('descripcion', models.TextField(verbose_name='Descripción del proyecto')),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('presupuestado', 'Presupuestado'), ('cerrado', 'Cerrado'), ('descartado', 'Descartado')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Solicitud de presupuesto',
                'verbose_name_plural': 'Solicitudes de presupuesto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=web.models.contact_image_path, verbose_name='Imagen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('contact_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.contactrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Imagen adjunta',
                'verbose_name_plural': 'Imágenes adjuntas',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
