# Generated by Django 6.0 on 2026-01-14 00:21

import django.db.models.deletion
import apps.leads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('location', models.CharField(blank=True, help_text='Ciudad o zona', max_length=150, verbose_name='Ubicación')),
                ('message', models.TextField(verbose_name='Mensaje/Descripción')),
                ('source', models.CharField(choices=[('web', 'Formulario web'), ('telefono', 'Llamada telefónica'), ('recomendacion', 'Recomendación'), ('otro', 'Otro')], default='web', max_length=30, verbose_name='Origen')),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('presupuestado', 'Presupuestado'), ('cerrado', 'Cerrado'), ('descartado', 'Descartado')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('privacy_accepted', models.BooleanField(default=False, help_text='Aceptación RGPD', verbose_name='Privacidad aceptada')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP del visitante (anti-spam)', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, help_text='Navegador del visitante', max_length=500, verbose_name='User Agent')),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Teléfono'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Contacto preferido')),
                ('urgency', models.CharField(blank=True, choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Urgencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='services.service', verbose_name='Servicio de interés')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Código único: ARYN-2025-001', max_length=20, unique=True, verbose_name='Referencia')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (€)')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('file', models.FileField(blank=True, help_text='Presupuesto en PDF', upload_to=apps.leads.models.budget_file_path, verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.leads.models.lead_image_path, verbose_name='Imagen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Imagen de lead',
                'verbose_name_plural': 'Imágenes de leads',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creado'), ('status_changed', 'Estado cambiado'), ('assigned', 'Asignado'), ('noted', 'Nota añadida'), ('updated', 'Actualizado')], max_length=50, verbose_name='Acción')),
                ('old_value', models.CharField(blank=True, max_length=100, verbose_name='Valor anterior')),
                ('new_value', models.CharField(blank=True, max_length=100, verbose_name='Valor nuevo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='leads.lead', verbose_name='Lead')),
                ('user', models.ForeignKey(blank=True, help_text='Quién realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de lead',
                'verbose_name_plural': 'Logs de leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='leads_lead_status_2b0e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'),
        ),
    ]
