# Generated by Django 6.0 on 2026-01-14 16:52

import apps.leads.models
import apps.leads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='file',
            field=models.FileField(blank=True, help_text='Presupuesto en PDF. Máximo 10MB', upload_to=apps.leads.models.budget_file_path, validators=[apps.leads.validators.validate_pdf_file], verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='leadimage',
            name='image',
            field=models.ImageField(help_text='Máximo 5MB. Formatos: JPG, PNG, WEBP', upload_to=apps.leads.models.lead_image_path, validators=[apps.leads.validators.validate_image_file], verbose_name='Imagen'),
        ),
    ]
