# Generated by Django 6.0.1 on 2026-02-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_budget_file_alter_leadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('web', 'Formulario web'), ('api', 'API REST'), ('telefono', 'Llamada telefónica'), ('recomendacion', 'Recomendación'), ('otro', 'Otro')], default='web', max_length=30, verbose_name='Origen'),
        ),
    ]
