# Generated by Django 6.0.1 on 2026-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_budget_file_alter_leadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadlog',
            name='action',
            field=models.CharField(choices=[('created', 'Creado'), ('status_changed', 'Estado cambiado'), ('assigned', 'Asignado'), ('note_added', 'Nota añadida'), ('edited', 'Editado'), ('updated', 'Actualizado')], max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='leadlog',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='Valor nuevo'),
        ),
        migrations.AlterField(
            model_name='leadlog',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='Valor anterior'),
        ),
    ]
