# Generated by Django 6.0.1 on 2026-03-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadlog_textfield_and_edited_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='urgency',
        ),
    ]
