# Generated by Django 6.0.1 on 2026-03-03 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Usuario intentado')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('path', models.CharField(blank=True, default='', help_text='Distingue entre paneles (admynstal, offynstal)', max_length=255, verbose_name='URL del intento')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Intento de login fallido',
                'verbose_name_plural': 'Intentos de login fallidos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='idx_login_user_time'), models.Index(fields=['ip_address', 'timestamp'], name='idx_login_ip_time')],
            },
        ),
    ]
